### ISSUE TITLE
Mobile speller killed in CI/CD

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-kal#1]
KAL has not built properly in a while. The [log file](https://github.com/giellalt/lang-kal/runs/23933111125) says this:

```sh
/usr/bin/hfst-compose  -F \
.generated/generator-mobilespeller-gt-norm-base.hfst mob_spellercorpus.surfweights.hfst \
-o .generated/generator-mobilespeller-gt-norm-freq_weighted.hfst
make[3]: *** [Makefile:2496: .generated/generator-mobilespeller-gt-norm-freq_weighted.hfst] Killed
```

I suspect it is an out-of-memory thing, KAL is known to be very memory hungry during compilation. Give the builder VM more RAM?

**Comment by dylanhand** [comment]
I increased `linux-02`'s memory to 28,000MiB from 24,000MiB and the [build now succeeds](https://divvun-tc.giellalt.org/tasks/IRyuLT4JQ8WI9ZzGKfV1YA).

**Comment by snomos** [comment]
Thanks, I have noticed the same. I consider this bug fixed.

**Comment by TinoDidriksen** [comment]
If not done already, I would also install `libgoogle-perftools-dev` and `export LD_PRELOAD=libtcmalloc_minimal.so` to drastically speed up the builds. See https://github.com/hfst/hfst/issues/507 for stats.

**Comment by dylanhand** [comment]
> If not done already, I would also install `libgoogle-perftools-dev` and `export LD_PRELOAD=libtcmalloc_minimal.so` to drastically speed up the builds. See [hfst/hfst#507](https://github.com/hfst/hfst/issues/507) for stats.

@snomos if this is something you'd like, please add it to https://github.com/orgs/divvun/projects/2

**Comment by snomos** [comment]
> @snomos if this is something you'd like, please add it to https://github.com/orgs/divvun/projects/2

Done.
